### ISSUE TITLE
❓ Q: switch case search

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [codeque-co/codeque#13]
so I tried to search for switch case constructs but failed. Only the text mode gives a result. What am I doing wrong?

**Comment by sschneider-ihre-pvs** [comment]
I tried to search for `switch` in exact mode in ts files

**Comment by jayu** [comment]
Gotcha, so when searching just for `switch` the query code is parsed and the `switch` is interpreted as regular identifier.

So you would find find variables named `switch` with that query.

In order to search for switch-case you should at at least add basic valid switch-case code into query, eg.

```
switch($$) {}
```

It's best to use `include` mode there, as most likely you switch-case constructs will contain more code than your query.

[Docs about search modes](https://codeque.co/docs#search-modes) 📜 

Try this [playground](https://codeque.co/playground?settings=eyJtb2RlIjoiaW5jbHVkZSIsImNhc2UiOiJzZW5zaXRpdmUiLCJxdWVyeSI6InN3aXRjaCgkJCkge30iLCJjb2RlIjoic3dpdGNoKGV4cHJlc3Npb24pIHsgXG4gICBjYXNlIGNvbnN0YW50LWV4cHJlc3Npb24xOiB7IFxuICAgICAgLy9zdGF0ZW1lbnRzOyBcbiAgICAgIGJyZWFrOyBcbiAgIH0gXG4gICBjYXNlIGNvbnN0YW50X2V4cHJlc3Npb24yOiB7IFxuICAgICAgLy9zdGF0ZW1lbnRzOyBcbiAgICAgIGJyZWFrOyBcbiAgIH0gXG4gICBkZWZhdWx0OiB7IFxuICAgICAgLy9zdGF0ZW1lbnRzOyBcbiAgICAgIGJyZWFrOyBcbiAgIH0gXG59ICJ9) 👇 

<kbd><img width="1007" alt="image" src="https://github.com/codeque-co/codeque/assets/11561585/ea42d520-79aa-40fa-9d86-0590fa96f05c"></kbd>
