### ISSUE TITLE
✨ FR: Better error messages for unsupported languages

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [codeque-co/codeque#14]
I tried to search a bit of SQL files through.

![image](https://github.com/codeque-co/codeque/assets/86342787/5942e030-77f3-416b-ada7-f40772c6f467)

And I have no idea what that error message wants to tell me.

**Comment by jayu** [comment]
Hello, thanks for feedback. 

The extension supports structural search only for TypeScript and JavaScript at the moment. More languages are planned in future. 

Well the error message is referring to syntax error in your query, simply because TypeScript parser cannot parse the code.

When I will introduce more programming languages, I will make sure the distinction between selected language is clear.

Right now I think the description in the extension readme and the instructions on the empty results page are enougth

<img width="1011" alt="image" src="https://github.com/codeque-co/codeque/assets/11561585/0437edf1-dda2-435e-999e-d0b11e877f0d">
