### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by KozlovSergeiSergeevich** [codeque-co/codeque#30]
- Issue Type: `Performance`
- Extension Name: `codeque`
- Extension Version: `0.27.0`
- OS Version: `Darwin arm64 22.6.0`
- VS Code version: `1.81.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/57/hc95nnsj6rb2yw66x2dgswfr0000gn/T/CodeQue.codeque-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jayu** [comment]
Hello! Thank you for the bug report.

Can you share more details about the the issue?

Is there any specific query that causes high CPU loads?

**Comment by KozlovSergeiSergeevich** [comment]
> 

Hi!
I have a big project that uses Apollo.
I wrote a search query
```js
$$$m
onCompleted: (


```

After that, performance problems started. Stopping or changing the search parameters doesn't help, trying to reset doesn't help either. Unfortunately I had to completely disable the expansion

**Comment by jayu** [comment]
I see, apologies for that.

It's a known issue that once you run problematic query it's hard or even impossible to 'escape' that state, because query will be re-run on restart.

I will work on fixing the problem, there are two things that can be done:
- forbid running queries that starts or ends with wildcard, because they most likely cause performance issues and they do not make much sense
- properly handle stopping search, right now it seems to not work, especially for text mode and query that has performance issue.

I will be working on those in next possible slot when I will have time for codeque.

To unblock yourself, you can try removing data that is stored by codeque extension - CodeQue stores last query and if you manage to clean that storage, you should restart vscode and get empty query to start with. This stack overflow[Stack overflow ](https://stackoverflow.com/questions/36746857/completely-uninstall-vs-code-extensions)  might help, but I can't check if it works. Be carefull to not remove all extensions this way

**Comment by jayu** [comment]
Hey @KozlovSergeiSergeevich, Issue with this query should be solved. 
I've also added a check that prevents from lockout that you've encounter. 
If a given query will not finish running, after vscode restart, it will be cleaned.

I've released version `0.28.0` that solves this problem and adds some new features 😊
