### ISSUE TITLE
Hyphenated words/strings are not searching and also not searching in HTML and CSS files.

### ISSUE THREAD

**Issue by abhijeet-shelhalkar** [codeque-co/codeque#5]
Hi,

CodeQue is cool but found some critical issues.

Created a folder containing these files `index.html`, `style.css` and `main.js`

**index.html**

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CodeQue</title>
  <link rel="stylesheet" href="style.css">
  <script type="text/javascript" src="main.js" async></script>
</head>

<body>
  <my-button label="Abhijeet"></my-button>
</body>

</html>
```

**style.css**

```
/* label: my-button */

body {
  display: block;
}
```

**main.js**

```
var label= 'my-button';
console.log(label);
```

**Issues**

1. when search for **label** :
_output:_ It only searches in *.js files.

2. when search for **my-button** :
_output:_ sometimes it searches in only *.js files and sometimes the result is blank.

**Comment by jayu** [comment]
Hey, thank you for your time!

CodeQue works only for JavaScript and TypeScript files right now, so html and css are not supported atm.

___

Note that there are two main search modes:
- structural search mode called [`include`](https://codeque.co/docs#include-search-mode)
- text search mode called [`text`](https://codeque.co/docs#text-search-mode)

To search for a string content in structural way, you have to use the following query:
```ts
('my-button')
```

Searching just for `my-button` in structural search modes will not work as you expect, because it will match subtraction of two variables: `my` and `button`


To search for a string content in text mode, the query will be simply

```ts
my-button
```

___

For query `label`

Structural search mode will look for identifier `label`, while text search mode will just look for text `label`

___

All search modes only search files with `js,ts,jsx,tsx,cjs,mjs,json` extensions

___

I think I will add support for all files extensions to `text` mode, but this will come later

**Comment by jayu** [comment]
I've recently added support for any type of file search in `text` mode.
So you can search HTML and CSS. It's not structural search, but I hope It's fine for now :)

**Comment by abhijeet-shelhalkar** [comment]
@jayu Thanks for the update...
